name: CI
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test
      - name: Build debug
        run: cargo build --verbose
      - name: Build release
        run: cargo build --verbose --release
